### ISSUE TITLE
tools/build ?

### ISSUE THREAD

**Issue by headupinclouds** [evaautomation/boost#1]
I have to make a similar clone to apply some patches, and would prefer to just fork this one, but the tools/build folder I need to patch is missing.  Any thoughts?

**Comment by codykrieger** [comment]
D'oh. I had a rule in my `~/.gitignore` that looked like this:

```
[Bb]uild
```

:neutral_face:

**Comment by codykrieger** [comment]
(All fixed.)

**Comment by codykrieger** [comment]
That said, I'd still probably recommend not forking this repo, because it's meant to be specific to our needs, so we may continue to delete parts of the sources we don't need (like the docs).
